version: '2'
services:
  web:
    container_name: jellyfish_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
  db:
    container_name: codelift_db
    image: postgres
