version: '2'
services:
  web:
    container_name: api
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    links:
      - db
  db:
    container_name: api_db
    image: postgres:9.4
