development: &default
  adapter: <%= ENV['DB_ADAPTER'] ||= 'postgresql' %>
  min_messages: warning
  database: postgres
  username: postgres
  encoding: utf8
  timeout: 5000
  pool: 2
  host: db

test:
  <<: *default
  database: jellyfish_test

production:
  <<: *default
  database: jellyfish_production

docker:
  adapter: <%= ENV['DB_ADAPTER'] ||= 'postgresql' %>
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password: <%= ENV['POSTGRES_PASS'] %>
  host: db
