development: &default
  adapter: postgresql
  database: jellyfish_development
  username: postgres
  host: 192.168.99.100
  port: 5432
  encoding: utf8
  min_messages: warning
  pool: 2
  timeout: 5000

development:
  <<: *default
  adapter:  postgresql
  database: jellyfish_development

test:
  <<: *default
  database: jellyfish_test

production:
  <<: *default
  database: jellyfish_production

docker:
  adapter: <%= ENV['DB_ADAPTER'] ||= 'postgresql' %>
  encoding: unicode
  database: postgres
  pool: 5
  username: postgres
  password: <%= ENV['POSTGRES_PASS'] %>
  host: db
